version: "3.9"

services:
  gui:
    build: 
      context: .
      dockerfile: Dockerfile
    image: demeulemeestertibe/rp-gui
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./dockerData:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
