version: "3.9"

services:
  gui:
    build: 
      context: .
      dockerfile: Dockerfile
    image: demeulemeestertibe/rp-gui
    ports:
      - "9000:9000"
    environment:
      - GRADIO_SERVER_PORT=9000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
