version: 0.1.0
name: voice_cloning_using_xtts
type: command
display_name: Clone voice using XTTS v2.0 model
description: Cloning the a voice using audiofiles and XTTS v2.0 model
inputs:
  data_folder:
    type: uri_folder
    optional: False
  language:
    type: string
    optional: False
  epochs:
    type: number
    optional: False
  grad_acum:
    type: number
    optional: False
  batch_size:
    type: number
    optional: False
  speaker_name:
    type: string
    optional: False
  max_audio_length:
    type: number
    optional: False
outputs:
  output_data:
    type: uri_folder
environment: azureml:aml-dataprep:0.1.3
code: ./code
resources:
  instance_count: 1
command: "python train.py --data_folder ${{inputs.data_folder}} --output_path ${{outputs.output_data}} \
  --language ${{inputs.language}} --epochs ${{inputs.epochs}} \
  --grad_acum ${{inputs.grad_acum}} --batch_size ${{inputs.batch_size}} \
  --speaker_name ${{inputs.speaker_name}} --max_audio_length ${{inputs.max_audio_length}} \
  "