/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MusP0si85hv
 */
import { Navbar } from "./navbar"

export function SongPage() {
  return (
    <div key="1" className="flex flex-col h-screen bg-gray-100 dark:bg-gray-900">
      <Navbar />
      <div className="flex h-full">
        <main className="flex-1 p-6 overflow-y-auto flex flex-col items-center">
          <h1 className="text-3xl font-bold mb-6 text-center">Voice conversion with So-vits</h1>
          <div className="grid grid-cols-3 gap-8">
            <div className="flex flex-col space-y-4 items-center">
              <h2 className="text-2xl font-semibold">Original vocals</h2>
              <audio controls>
                <source src="/audio/songs/PretVocals.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <h2 className="text-2xl font-semibold">Speaker vocals</h2>
              <audio controls>
                <source src="/audio/songs/nathanPret.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <h2 className="text-2xl font-semibold">Full song</h2>
              <audio controls>
                <source src="/audio/songs/nathanPret&RoapnFull.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <audio controls>
                <source src="/audio/songs/vocalsMambo.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <audio controls>
                <source src="/audio/songs/nathanMambo.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <audio controls>
                <source src="/audio/songs/nathanMambo5Full.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <audio controls>
                <source src="/audio/songs/pianomanvocals.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <audio controls>
                <source src="/audio/songs/nathanPianoman.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
            <div className="flex flex-col space-y-4 items-center">
              <audio controls>
                <source src="/audio/songs/nathanPianomanFull.wav" type="audio/wav" />
                Your browser does not support the audio element.
              </audio>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
