/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nvwXEypeh56
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function SpeechSynthesize() {
  return (
    <div key="1" className="flex flex-col h-screen bg-gray-100 dark:bg-gray-900">
      <nav className="bg-white dark:bg-gray-800 border-b dark:border-gray-700 p-4">
        <div className="flex justify-between items-center">
          <h1 className="text-2xl font-semibold">Research Project</h1>
          <div className="flex gap-4">
            <Link className="text-gray-600 dark:text-gray-300 hover:text-blue-500 dark:hover:text-blue-400" href="#">
              Demo
            </Link>
            <Link className="text-gray-600 dark:text-gray-300 hover:text-blue-500 dark:hover:text-blue-400" href="#">
              Speech Synthesis
            </Link>
            <Link className="text-gray-600 dark:text-gray-300 hover:text-blue-500 dark:hover:text-blue-400" href="#">
              Songs
            </Link>
          </div>
        </div>
      </nav>
      <div className="flex h-full">
        <main className="flex-1 p-6 overflow-y-auto space-y-6 flex flex-col items-center">
          <h2 className="text-3xl font-bold mb-4">Synthesize Speech Using Reference Audio</h2>
          <div className="flex items-center gap-4 w-full max-w-lg">
            <Label htmlFor="audio-upload">Upload Audio</Label>
            <Input accept="audio/*" id="audio-upload" type="file" />
          </div>
          <div className="flex flex-col gap-4 w-full max-w-lg">
            <div className="flex justify-between items-center">
              <Label htmlFor="reference-audio">Reference Audio</Label>
              <div className="flex-1">
                <audio controls id="reference-audio">
                  <source src="/placeholder-audio.mp3" type="audio/mpeg" />
                  Your browser does not support the audio element.
                </audio>
              </div>
            </div>
            <div className="flex justify-between items-center">
              <Label htmlFor="audio-result">Result Audio</Label>
              <div className="flex-1">
                <audio controls id="audio-result">
                  <source src="/placeholder-audio.mp3" type="audio/mpeg" />
                  Your browser does not support the audio element.
                </audio>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-4 w-full max-w-lg absolute bottom-10">
            <Input className="flex-1" id="synthesize-text" placeholder="Enter text to synthesize" type="text" />
            <Button className="ml-4 bg-black text-white">Synthesize</Button>
          </div>
        </main>
      </div>
    </div>
  )
}
