/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nvwXEypeh56
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function SpeechSynthesize() {
  return (
    <div key="1" className="flex flex-col h-screen bg-gray-100 dark:bg-gray-900">
      <div className="flex h-full">
        <main className="flex-1 p-6 overflow-y-auto space-y-6 flex flex-col items-center">
          <h2 className="text-3xl font-bold mb-4">Synthesize Speech Using Reference Audio</h2>
          <div className="flex items-center justify-between gap-8 w-full max-w-lg">
            <Label htmlFor="audio-upload">Upload Audio</Label>
            <Input accept="audio/*" className="flex w-3/5" id="audio-upload" type="file" />
          </div>
          <div className="flex flex-col gap-8 w-full max-w-lg">
            <div className="flex gap-4 justify-between items-center">
              <Label htmlFor="reference-audio">Reference Audio</Label>
              <div className="">
                <audio controls id="reference-audio">
                  <source src="/placeholder-audio.mp3" type="audio/wav" />
                  Your browser does not support the audio element.
                </audio>
              </div>
            </div>
            <div className="flex gap-4 justify-between items-center">
              <Label htmlFor="audio-result">Result Audio</Label>
              <div className="">
                <audio controls id="audio-result">
                  <source src="/placeholder-audio.mp3" type="audio/wav" />
                  Your browser does not support the audio element.
                </audio>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-4 w-full max-w-lg absolute bottom-10">
            <Input className="flex-1" id="synthesize-text" placeholder="Enter text to synthesize" type="text" />
            <Button className="ml-4 bg-black text-white" variant={"dark"}>Synthesize</Button>
          </div>
        </main>
      </div>
    </div>
  )
}
