version: "3.9"

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: demeulemeestertibe/rp-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: demeulemeestertibe/rp-web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app