version: "3.9"

services:
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: demeulemeestertibe/rp-api
    ports:
      - "8000:8000"
    expose:
      - 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - api.env
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 15s
      timeout: 10s
      retries: 3

  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: demeulemeestertibe/rp-web
    ports:
      - "3000:3000"
    networks:
      - api-network
    depends_on:
      api:
        condition: service_healthy

networks:
  api-network:
